namespace ATTicket.Domain.Repositories.AppDbContext.UserAndCompanyRelationshipRepositories;
public interface IUserAndCompanyRelationshipCommandRepository : IAppCommandRepository<UserAndCompanyRelationship>{}
