namespace ATTicket.Domain.Repositories.CompanyDbContext.TicketSolution;
internal interface ITicketSolutionCommandRepository:ICompanyDbCommandRepository<ATTicket.Domain.CompanyEntities.TicketSolution>{}
