namespace ATTicket.Domain.Repositories.CompanyDbContext.TicketPdfDetail;
public interface ITicketPdfDetailCommandRepository:ICompanyDbCommandRepository<ATTicket.Domain.CompanyEntities.TicketPdfDetail>{}
