namespace ATTicket.Domain.Repositories.CompanyDbContext.OutGoingMailSettings;
public interface IOutGoingMailSettingsCommandRepository:ICompanyDbCommandRepository<ATTicket.Domain.CompanyEntities.OutGoingMailSettingses>{}
